### ISSUE TITLE
Data container crashes

### ISSUE THREAD

**Issue by bradddd** [realpython/orchestrating-docker#3]
Ultimately during the `docker-compose up` call, the data container exits and causes the other 3 containers to shutdown:

```
orchestratingdocker_data_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
Stopping orchestratingdocker_nginx_1... done
Stopping orchestratingdocker_web_1... done
Stopping orchestratingdocker_postgres_1... done
Stopping orchestratingdocker_data_1... done
```

I haven't altered any of the code from the repo. It works fine if I comment out the data container and the relevant lines from the postgres container.

I'm on a mac. Here are the versions if it helps:

```
$ docker-machine --version
docker-machine version 0.4.1 (e2c88d6)
$ docker -v
Docker version 1.8.1, build d12ea79
$ docker-compose --version
docker-compose version: 1.4.0
```

**Comment by bradddd** [comment]
So I think my diagnosis was wrong. The data container definitely exits 0, but I don't think that's an issue per se. I went back to this and tried it in Ubuntu 14.04, and I'm running into the same issue. 

I was able to get it working though. If I change the `restart` value for the data container to `no`, it works.

Anyone have any idea why this is? Is it working for people with `restart: always`?

**Comment by mjhea0** [comment]
updated! changed `restart` to `no`. thanks!
