### ISSUE TITLE
docker-compose build fails with CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by freyp567** [realpython/orchestrating-docker#6]
I tried to run the steps in https://realpython.com/blog/python/dockerizing-flask-with-compose-and-machine-from-localhost-to-the-cloud/ and got up to step "build the images and then start the services"

docker-compose build fails with ERROR
SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

I have Docker Toolbox on my notebook (Windows), installed yesterday
up and running

$ docker-machine --version
docker-machine.exe version 0.6.0, build e27fb87

$ docker-compose --version
docker-compose version 1.6.2, build e80fc83

$ docker --version
Docker version 1.10.3, build 20f81dd

**Comment by mjhea0** [comment]
Make sure you are using the same Docker versions as I am in the post -> https://realpython.com/blog/python/dockerizing-flask-with-compose-and-machine-from-localhost-to-the-cloud/#local-setup. Try that and if you are still having problems be sure to open this issue back up.

**Comment by freyp567** [comment]
cause of problem found, it was not the docker versions but a http proxy problem
I had both HTTP_PROXY and HTTPS_PROXY set, as I usually need that when working in the office, and in homeoffice it should do, too, through VPN. But unfortunately doesnt

unset HTTP_PROXY
unset HTTPS_PROXY

before the 'docker-compose build'
did resolve my problem
