### ISSUE TITLE
error while building

### ISSUE THREAD

**Issue by buddiex** [realpython/orchestrating-docker#9]
i get this error while using building.  kindly help.

orchestrating-docker$ docker-compose up
Building web
Step 1 : FROM python:3.4-onbuild
# Executing 3 build triggers...

Step 1 : COPY requirements.txt /usr/src/app/
 ---> Using cache
Step 1 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Running in 9c8b343de8e1
Collecting Flask==0.10.1 (from -r requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f5e2d1b00b8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/flask/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f5e2d1b0e80>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/flask/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f5e2d1b0898>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/flask/

**Comment by mjhea0** [comment]
Which version of Docker are you using?
